Feature/joi
techmodel/techmodel-back pull request #17
Opened 2022-07-17 21:06 UTC by Itay9263

2022-07-18 17:14 UTC, Hyaxia commented on src/exc.ts
> +    Object.setPrototypeOf(this, CannotPerformOperationError.prototype);
small copy paste fix - change `CannotPerformOperationError` to `ObjectValidationError`

2022-07-18 17:14 UTC, Hyaxia commented on src/api/volunteerRequest.ts
> +router.put('/:id', async (req: Request, res: Response, next: NextFunction) => {
add swagger docs to the route

2022-07-18 17:22 UTC, Hyaxia commented on src/api/volunteerRequest.ts
> +  .post(async (req: Request, res: Response, next: NextFunction) => {
missing `authMiddleware`

2022-07-18 17:22 UTC, Hyaxia commented on src/app/volunteerRequest.ts
> +  if (!id) throw new BadRequestError('Missing Id to update volunteer request by');
missing checks who can update the volunteer request

2022-07-18 17:23 UTC, Hyaxia commented on src/api/volunteerRequest.ts
>    try {
missing `authMiddleware`

2022-07-18 17:25 UTC, Hyaxia commented on src/app/volunteerRequest.ts
> +  return volunteerRequestRepository.save(validateSchema(volunteerRequestSchema, volunteerRequest));
missing checks for creation of the volunteer request, for example, if the user is from institution id 1, then the volunteer request must have also institution id 1. I'm sure there are more validations to make besides that.

2022-07-18 17:28 UTC, Hyaxia commented on src/app/schema.validators.ts
> +    then: onlyNull,
why is it `onlyNull`?

2022-07-18 17:36 UTC, Hyaxia commented on src/app/user.ts
>  export const register = async (user: Partial<User>): Promise<loginResponse> => {
can we ask the UI to send us a token that will signal that the user has been authenticated by google or something similar? so not every request sent to this route will be processed but only those that have been authentiacted

2022-07-18 17:38 UTC, Hyaxia requested changes
besides the other comments, tests for each new use case should be added.
if you want me to help you swagger docs or something else tell me

2022-07-18 17:41 UTC, Itay9263 commented on src/api/volunteerRequest.ts
> +    const id = +req.params.id;
yep

2022-08-09 11:52 UTC, Hyaxia approved these changes

2022-08-09 11:53 UTC, merged